# Generated by Django 5.2.12 on 2026-03-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
