# Generated by Django 5.2.12 on 2026-03-08 02:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('vegetables', 'Vegetables'), ('bakery', 'Bakery'), ('restaurant', 'Restaurant'), ('supermarket', 'Supermarket')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('town', models.CharField(max_length=100)),
                ('delivery_type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('both', 'Both')], default='both', max_length=10)),
                ('estimated_delivery_time', models.IntegerField(default=30, help_text='in minutes')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('food', 'Food'), ('grocery', 'Grocery'), ('other', 'Other')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor')),
            ],
        ),
    ]
