# Generated by Django 5.2.12 on 2026-03-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='delivery_radius',
            field=models.FloatField(default=5.0),
        ),
    ]
