# Generated by Django 5.2.12 on 2026-04-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST % e.g. 5, 12, 18', max_digits=5),
        ),
    ]
