# Generated by Django 5.2.12 on 2026-04-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_product_gst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=8, null=True),
        ),
    ]
