# Generated by Django 5.2.12 on 2026-04-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_product_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
