# Generated by Django 5.2.12 on 2026-04-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_productvariant_mrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='mrp',
        ),
    ]
