# Generated by Django 5.2.12 on 2026-04-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_productvariant_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
