# Generated by Django 5.2.12 on 2026-04-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_productvariant_delivery_time_productvariant_hsn_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_cod',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='is_returnable',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='subcategory',
        ),
    ]
