# Generated by Django 5.2.12 on 2026-04-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_remove_productvariant_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_cod',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
