# Generated by Django 5.2.12 on 2026-05-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_product_delivery_time_product_hsn_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
