# Generated by Django 5.2.12 on 2026-04-01 14:32

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=orders.models.generate_order_number, editable=False, max_length=20),
        ),
    ]
