# Generated by Django 5.2.12 on 2026-04-01 14:33

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_fee_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=orders.models.generate_order_number, editable=False, max_length=20, unique=True),
        ),
    ]
